---
ACL:
  opaque: |
    Q0ECAHQFCAAAAAAABQDQAxAAIARABAEAAAAoAAQAAAAEACgAoQMNADEzLzA1LzIwMjUgMDk6MzA6Mzcg
    UE0gU2VyZGFyIEJhc2VnbWV6L2RldmVsb3BpIHVwZGF0ZWQgT3RoZXJEb21haW5TZXJ2ZXJzADI2LzAz
    LzIwMjQgMDk6MDI6MzYgUE0gU2VyZGFyIEJhc2VnbWV6L2RldmVsb3BpIHVwZGF0ZWQgTlNGT0RQUmVt
    b3RlVXNlcgAyNi8wMy8yMDI0IDA5OjAyOjAxIFBNIFNlcmRhciBCYXNlZ21lei9kZXZlbG9waSB1cGRh
    dGVkIE5TRk9EUFJlbW90ZVVzZXIAMjYvMDMvMjAyNCAwOTowMTo1NyBQTSBTZXJkYXIgQmFzZWdtZXov
    ZGV2ZWxvcGkgYWRkZWQgTlNGT0RQUmVtb3RlVXNlcgAyNi8wMy8yMDI0IDA4OjU5OjA3IFBNIFNlcmRh
    ciBCYXNlZ21lei9kZXZlbG9waSB1cGRhdGVkIExvY2FsRG9tYWluQWRtaW5zADI2LzAzLzIwMjQgMDg6
    NTk6MDEgUE0gU2VyZGFyIEJhc2VnbWV6L2RldmVsb3BpIGFkZGVkIExvY2FsRG9tYWluQWRtaW5zADI2
    LzAzLzIwMjQgMDg6NTg6NTQgUE0gU2VyZGFyIEJhc2VnbWV6L2RldmVsb3BpIHVwZGF0ZWQgLURlZmF1
    bHQtADI2LzAzLzIwMjQgMDg6NTg6NDcgUE0gU2VyZGFyIEJhc2VnbWV6L2RldmVsb3BpIGFkZGVkIEFu
    b255bW91cwAyNi8wMy8yMDI0IDA1OjQwOjQ1IFBNIFNlcmRhciBCYXNlZ21lei9kZXZlbG9waSBhZGRl
    ZCBPdGhlckRvbWFpblNlcnZlcnMAMjYvMDMvMjAyNCAwNTo0MDo0NSBQTSBTZXJkYXIgQmFzZWdtZXov
    ZGV2ZWxvcGkgYWRkZWQgTG9jYWxEb21haW5TZXJ2ZXJzADI2LzAzLzIwMjQgMDU6NDA6NDUgUE0gU2Vy
    ZGFyIEJhc2VnbWV6L2RldmVsb3BpIGFkZGVkIG1hZ2dpZS9kZXZlbG9waQAyNi8wMy8yMDI0IDA1OjQw
    OjQ1IFBNIFNlcmRhciBCYXNlZ21lei9kZXZlbG9waSBhZGRlZCBTZXJkYXIgQmFzZWdtZXovZGV2ZWxv
    cGkAMjYvMDMvMjAyNCAwNTo0MDo0NSBQTSBTZXJkYXIgQmFzZWdtZXovZGV2ZWxvcGkgdXBkYXRlZCAt
    RGVmYXVsdC0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABOBeIEkAQAAAAACgUAAAAAAAAAACgF
    AABeBAAAAAAAAEVBBAAAAAAAAAAAAAAABAYJAC1EZWZhdWx0LQAAAEVBBgAAAAAAAAAAAAAAuAcdAENO
    PVNlcmRhciBCYXNlZ21lei9PPWRldmVsb3BpAAAARUEGAAAAAAAAAAAAAACahxQAQ049bWFnZ2llL089
    ZGV2ZWxvcGkAAAAARUEGAAAAAAAAAAAAAADaBxIATG9jYWxEb21haW5TZXJ2ZXJzAAAAAEVBBQAAAAAA
    AAAAAAAA2gcSAE90aGVyRG9tYWluU2VydmVycwAAAABFQQAAAAAAAAAAAAAAAAUQCQBBbm9ueW1vdXMA
    ugRFQQYAAAAAAAAAAAAAAPgHEQBMb2NhbERvbWFpbkFkbWlucwAAAEVBBQAAAAAAAAAAAAAA+AcQAE5T
    Rk9EUFJlbW90ZVVzZXIAAA==
DBOptions: 0x00000000
DBInfo:
  FTIndexPriority: 3
  FTOptions: 0x0044
  FTStopFile: ""
  FTThesaur: ""
  Flags: 0x0000
  MajorVersion: 1
  MinorVersion: 0
  Options: 0x0000
  Spare1: 0